#!/bin/bash

#For Bash for windows - no translate patsh linux -> windows
declare -x MSYS_NO_PATHCONV=1

#PHP Composer run through Docker container
PWD=$(pwd)
#echo "Current working directory: '${PWD}'"

if [ "x$@" != "x" ]; then
	if [ "$@" == "dump-autoload" ] ;then
		docker run --rm -v "${PWD}":/app composer/composer533 $@
	else
		docker run --rm -v "${PWD}":/app composer/composer533 --ignore-platform-reqs $@
	fi
else
	docker run --rm -v "${PWD}":/app composer/composer533 
fi
